routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('', 'order/list');
Route::get('shared/read-file/{hash}', 'SharedController@readFile');
Route::get('shared/terms-of-use', 'SharedController@termsOfuse');

// TODO: удалить shared/fake-api
Route::post('shared/fake-api/orders', 'SharedController@fakeApi');
Route::post('shared/fake-api/samples', 'SharedController@fakeApi');
Route::post('shared/fake-api/claims', 'SharedController@fakeApi');
Route::post('shared/fake-api/chats', 'SharedController@fakeApi');
Route::post('shared/fake-api/consignees', 'SharedController@fakeApi');

// Авторизация
Route::get('login', 'AuthController@showLoginForm')->name('login');
Route::post('login', 'AuthController@login');
Route::post('logout', 'AuthController@logout');

// Личный кабинет
Route::group(['middleware' => 'auth'], function() {

    // Заявки
    Route::group(['prefix' => 'order'], function() {
        Route::redirect('', 'order/list');
        Route::get('list', 'OrderController@index');
        Route::get('create', 'OrderController@create');
        Route::get('edit/{id}', 'OrderController@edit');
        Route::post('copy/{id}', 'OrderController@copy');
        Route::get('show/{id}', 'OrderController@show');
        Route::post('delete/{id}', 'OrderController@delete');
        // ajax
        Route::post('ajax-store', 'OrderController@ajaxStore');
        Route::post('ajax-update/{id}', 'OrderController@ajaxUpdate');
        Route::post('ajax-remember-client', 'OrderController@ajaxRememberClient');
        Route::post('ajax-filter-nomenclatures', 'OrderController@ajaxFilterNomenclatures');
        Route::post('ajax-validate-order', 'OrderController@ajaxValidateOrder');
        Route::post('ajax-validate-order-item', 'OrderController@ajaxValidateOrderItem');
        Route::post('ajax-load-more', 'OrderController@ajaxLoadMore');
    });

    // Образцы
    Route::group(['prefix' => 'sample'], function() {
        Route::redirect('', 'sample/list');
        Route::get('list', 'SampleController@index');
        Route::get('create', 'SampleController@create');
        Route::get('edit/{id}', 'SampleController@edit');
        Route::post('copy/{id}', 'SampleController@copy');
        Route::get('show/{id}', 'SampleController@show');
        Route::post('delete/{id}', 'SampleController@delete');
        // ajax
        Route::post('ajax-store', 'SampleController@ajaxStore');
        Route::post('ajax-update/{id}', 'SampleController@ajaxUpdate');
        Route::post('ajax-remember-client', 'SampleController@ajaxRememberClient');
        Route::post('ajax-validate-sample', 'SampleController@ajaxValidateSample');
        Route::post('ajax-load-more', 'SampleController@ajaxLoadMore');
    });

    // Претензии
    Route::group(['prefix' => 'claim'], function() {
        Route::redirect('', 'claim/list');
        Route::get('list', 'ClaimController@index');
        Route::get('create', 'ClaimController@create');
        Route::get('edit/{id}', 'ClaimController@edit');
        Route::get('show/{id}', 'ClaimController@show');
        Route::post('delete/{id}', 'ClaimController@delete');
        // ajax
        Route::post('ajax-store', 'ClaimController@ajaxStore');
        Route::post('ajax-update/{id}', 'ClaimController@ajaxUpdate');
        Route::post('ajax-remember-client', 'ClaimController@ajaxRememberClient');
        Route::post('ajax-validate-claim', 'ClaimController@ajaxValidateClaim');
        Route::post('ajax-load-more', 'ClaimController@ajaxLoadMore');
    });

    // Профиль
    Route::group(['prefix' => 'profile', 'middleware' => 'client'], function() {
        Route::redirect('', 'profile/info');
        Route::get('info', 'ProfileController@info');
        Route::get('agreements', 'ProfileController@agreements');
        Route::get('consignees', 'ProfileController@consignees');
        Route::get('nomenclatures', 'ProfileController@nomenclatures');
        // ajax
        Route::post('ajax-validate-consignee', 'ProfileController@ajaxValidateConsignee');
        Route::post('ajax-handle-consignee', 'ProfileController@ajaxHandleConsignee');
        Route::post('ajax-check-consignee-extid', 'ProfileController@ajaxCheckConsigneeExtId');
    });

    // Чат
    Route::group(['prefix' => 'chat'], function() {
        // ajax
        Route::post('ajax-store', 'ChatController@ajaxStore');
        Route::post('ajax-get-unread', 'ChatController@ajaxGetUnread');
    });
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use App\Models\OrderItem;
use App\Models\File;

class Order extends Model
{
    /**
     * Базовые поля даты
     * 
     * @var bool
     */
    public $timestamps = false;

    /**
     * Статусы
     * 
     * @var array
     */
    public static $statusTypes = [
        'new' => 'Новая',
        'confirmed' => 'Подтверждена',
        'production' => 'Передана в производство',
        'ready' => 'Готова к отгрузке',
        'done' => 'Выполнена',
        'canceled' => 'Отменена'
    ];

    /**
     * Типы доставки
     * 
     * @var array
     */
    public static $deliveryTypes = [
        'delivery' => 'Доставка',
        'pickup' => 'Самовывоз'
    ];

    /**
     * Варианты даты
     * 
     * @var array
     */
    public static $dateTypes = [
        // 'date' => 'По дате заявки',
        'desired_date' => 'По дате отгрузки',
        'ready_date' => 'По дате доставки',
    ];

    /**
     * Правила валидации
     * 
     * @var array
     */
    public static $rules = [
        'user_id' => 'required',
        'buyer_ext_id' => 'required',
        'consignee_id' => 'required',
        'agreement_id' => 'required',
        'delivery_type' => 'required',
        'desired_date' => 'required',
        'request_number' => 'nullable|order_unique_request_number',
        'items' => 'order_items_required|order_items_min',
        'file' => 'filled|max:10000|mimes:jpg,jpeg,png,tiff,bmp,doc,docx,xls,xlsx,pdf,zip,rar'
    ];

    /**
     * Сообщения для правил валидации
     * 
     * @var array
     */
    public static $rulesMessages = [
        'user_id.required' => 'Не найден ID клиента.',
        'buyer_ext_id.required' => 'Не выбран «Покупатель».',
        'consignee_id.required' => 'Не выбран «Грузополучатель».',
        'agreement_id.required' => 'Не выбран «Договор».',
        'delivery_type.required' => 'Не выбран «Тип доставки».',
        'desired_date.required' => 'Отсутствует «Дата отгрузки/доставки».',
        'request_number.order_unique_request_number' => '«Внутренний № заявки» должен быть уникален.',
        'items.order_items_required' => 'Отсутствуют «Позиции».',
        'items.order_items_min' => 'Объем заявки меньше необходимого.',
        'file.uploaded' => 'Загрузка файла не удалась.',
        'file.max' => 'Максимальный объем файла 10Mb.',
        'file.mimes' => 'Формат файла должен быть: jpg, jpeg, png, tiff, bmp, doc, docx, xls, xlsx, pdf, zip, rar.'
    ];

    /**
     * Правила валидации api
     * 
     * @var array
     */
    public static $apiRules = [
        'get' => [
            'order_id' => 'required'
        ],
        'update' => [
            'order_id' => 'required',
            'buyer_id' => 'filled',
            'consignee_id' => 'filled',
            'agreement_id' => 'filled',
            'delivery_type' => 'filled|in:delivery,pickup',
            'desired_date' => 'filled',
            'status' => 'filled|in:new,confirmed,production,ready,done,canceled',
            'product_code' => 'filled'
        ],
        'delete' => [
            'order_id' => 'required'
        ],
    ];

    /**
     * Сообщения для правил валидации api
     * 
     * @var array
     */
    public static $apiRulesMessages = [
        'required' => 'Поле обязательно для заполнения.',
        'filled' => 'Поле обязательно для заполнения.',
    ];

    /**
     * Название таблицы
     * 
     * @var string
     */
    protected $table = 'order';

    /**
     * Первичный ключ
     * 
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Клиент заявки
     * 
     * @return \App\Models\User
     */
    public function client()
    {
        return $this->hasOne(
                'App\Models\User',
                'id',
                'user_id'
            );
    }

    /**
     * Покупатель
     * 
     * @return \App\Models\UserAgreement
     */
    public function buyer()
    {
        return $this->hasOne(
                'App\Models\UserAgreement',
                'buyer_ext_id',
                'buyer_ext_id'
            );
    }

    /**
     * Грузополучатель
     * 
     * @return \App\Models\UserConsignee
     */
    public function consignee()
    {
        return $this->hasOne(
                'App\Models\UserConsignee',
                'id',
                'consignee_id'
            );
    }

    /**
     * Договор
     * 
     * @return \App\Models\UserAgreement
     */
    public function agreement()
    {
        return $this->hasOne(
                'App\Models\UserAgreement',
                'id',
                'agreement_id'
            );
    }

    /**
     * Позиции
     * 
     * @return \App\Models\OrderItem
     */
    public function items()
    {
        return $this->hasMany(
                'App\Models\OrderItem',
                'order_id',
                'id'
            );
    }

    /**
     * Доверенность для водителя
     * 
     * @return \App\Models\File
     */
    public function file()
    {
        return $this->hasOne(
                'App\Models\File',
                'object_id',
                'id'
            )
            ->where('object_type', 'order');
    }

    /**
     * Чат
     * 
     * @return \App\Models\File
     */
    public function chat()
    {
        return $this->hasMany(
                'App\Models\Chat',
                'object_id',
                'id'
            )
            ->where('object_type', 'order')
            ->orderBy('date', 'desc');
    }

    /**
     * Найти по id
     * 
     * @param int $id
     * @return mixed
     */
    public static function oneById($id)
    {
        return self::with([
                'client',
                'buyer',
                'consignee',
                'agreement',
                'items.nomenclature.type',
                'items.nomenclature.cardboardType',
                'items.nomenclature.cardboardProfile',
                'items.nomenclature.cardboardColor',
                'file' => function($query) {
                    $query->select('id', 'object_id', 'name', 'hash');
                },
                'chat.files' => function($query) {
                    $query->select('id', 'object_id', 'name', 'hash');
                },
            ])
            ->find($id);
    }

    /**
     * Найти по ext_id
     * 
     * @param string $extId
     * @return mixed
     */
    public static function oneByExtId($extId)
    {
        return self::with([
                'client',
                'buyer',
                'consignee',
                'agreement',
                'items.nomenclature.type',
                'items.nomenclature.cardboardType',
                'items.nomenclature.cardboardProfile',
                'items.nomenclature.cardboardColor',
                'file' => function($query) {
                    $query->select('id', 'object_id', 'name', 'hash');
                },
                'chat.files' => function($query) {
                    $query->select('id', 'object_id', 'name', 'hash');
                },
            ])
            ->where('ext_id', $extId)
            ->first();
    }

    /**
     * Список для претензии клиента
     * 
     * @param int $userId
     * @return mixed
     */
    public static function allForClaim($userId)
    {
        return self::with([
                'client',
                'items.nomenclature'
            ])
            ->where('user_id', $userId)
            ->where('status', '!=', 'canceled')
            ->whereNotNull('ext_id')
            ->get();
    }

    /**
     * Список с учетом типа аккаунта пользователя (ЛК)
     * 
     * @param array $filters
     * @return mixed
     */
    public static function allForAccountType($filters)
    {
        $query = self::prepareForAccountType($filters);
        
        return $query->skip($filters['offset'])
            ->take($filters['limit'])
            ->orderBy('date', 'desc')
            ->get();
    }

    /**
     * Кол-во с учетом типа аккаунта пользователя (ЛК)
     * 
     * @param array $filters
     * @return mixed
     */
    public static function countForAccountType($filters)
    {
        $query = self::prepareForAccountType($filters);
        
        return $query->count();
    }
    
    /**
     * Подготовительный запрос с учетом типа аккаунта пользователя (ЛК)
     * 
     * @param array $filters
     * @return mixed
     */
    protected static function prepareForAccountType($filters)
    {
        $query = self::with([
            'client',
            'items.nomenclature.type',
            'items.nomenclature.cardboardType',
            'items.nomenclature.cardboardProfile',
            'items.nomenclature.cardboardColor',
        ])
        ->withCount(['chat' => function($query) {
            if (user_account_type('admin'))
                $query->where('read_by_admin', 0);
            if (user_account_type('manager'))
                $query->where('read_by_manager', 0);
            if (user_account_type('client'))
                $query->where('read_by_client', 0);
        }]);

        // Определение аккаунта
        if (user_account_type('client'))
            $query->where('user_id', Auth::user()->id);

        if (user_account_type('manager'))
        {
            $query->whereIn('user_id', function($query) {
                $query->select('id')
                    ->from('user')
                    ->where('manager_id', Auth::user()->id);
            });
        }

        // Фильтры
        if ($filters['date_range'] != '')
        {
            $row = explode(' ', str_replace('/\s(.*)\s/', ' ', $filters['date_range']));
            $query->whereBetween('date', [to_db_datetime($row[0]), to_db_datetime($row[2])]);
        }

        if ($filters['status'] != '')
            $query->where('status', $filters['status']);

        if ($filters['client'] != '')

resources/views/order/inc/_js_form.blade.php
<script id="js-buyer-agreements" type="text/template">
    <option value="">Выбрать договор</option>
    <% _.each(items, function (agreement, key) { %>
        <option value="<%= agreement.id %>" data-agreement='<%= JSON.stringify(agreement) %>'>№ <%= agreement.number %> от <%= to_agreement_date(agreement.date) %></option>
    <% }); %>
</script>

<script id="js-modal-nomenclatures" type="text/template">
    <% _.each(items, function (nomenclature, key) { %>
        <tr data-nomenclature='<%= JSON.stringify(nomenclature) %>' class="<%= (_.contains(selected_ids, nomenclature.id)) ? 'disabled' : '' %>">
            <td><%= nomenclature.title %></td>
            <td><%= (nomenclature.sku) ? nomenclature.sku : '—' %></td>
            <td><%= nomenclature.cardboard_type.title %></td>
            <td><%= (nomenclature.print == 1) ? 'да' : 'нет' %></td>
            <%
                var area = Number(nomenclature.area).toLocaleString('en-US', {maximumFractionDigits: 2, minimumFractionDigits: 2}).replace(/,/i, ' ');
                if (String(area).search(/\.00/i) > 0) {
                    area = String(area).replace(/\.00/i, '');
                }
            %>
            <td><%= area %></td>
        </tr>
    <% }); %>
</script>

<script id="js-order-position" type="text/template">
    <div class="order-position-item" data-id="<%= item.id %>" data-search-nomenclature-sku="<%= item.nomenclature.sku %>" data-search-nomenclature-title="<%= item.nomenclature.title %>" data-selected-nomenclature-id="<%= item.nomenclature.id %>" data-nomenclature='<%= JSON.stringify(item.nomenclature) %>'>
        <div>
            <% if (item.address != '' && Number(item.address_number) > 0) { %>
                <span class="order-position-number"><%= item.address_number %></span>
            <% } %>
            <%= item.address %>
        </div>
        <div>
            <a href="#" class="order-position-code u u-dotted" data-toggle="tooltip" title="<%= item.comment %>"><%= item.sku %></a>
            <span>Код изделия</span>
        </div>
        <div>
            <%= item.title %>
            <span><%= (item.nomenclature.print == 1) ? 'С печатью' : 'Без печати' %></span>
        </div>
        <div>
            <%= Number(item.cnt).toLocaleString().replace(/,/i, ' ') %>
            <span>Кол-во</span>
        </div>
        <div>
            <%
                var area;
                if (Number(item.cnt) > 1) {
                    area = Number(item.cnt) * Number(item.area);
                    area = Number(area).toLocaleString('en-US', {maximumFractionDigits: 2, minimumFractionDigits: 2}).replace(/,/i, ' ');
                    if (String(area).search(/\.00/i) > 0) {
                        area = String(area).replace(/\.00/i, '');
                    }
                } else {
                    area = Number(item.area).toLocaleString('en-US', {maximumFractionDigits: 2, minimumFractionDigits: 2}).replace(/,/i, ' ');
                    if (String(area).search(/\.00/i) > 0) {
                        area = String(area).replace(/\.00/i, '');
                    }
                }
            %>
            <%= area %>
            <span>Итоговая площадь,&nbsp;м²</span>
            <div class="popup-menu-container">
                <div class="icon-more js-show-popup-menu"></div>
                <div class="popup-menu">
                    <ul>
                        <li><a href="#" class="edit-position" data-id="<%= item.id %>">Изменить</a></li>
                        <li><a href="#" class="delete-position" data-id="<%= item.id %>">Удалить</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</script>

<script id="js-validation-errors" type="text/template">
    <div class="alert alert-danger">
        <ul>
            <% _.each(items, function (error) { %>
                <li><%= error[0] %></li>
            <% }); %>
        </ul>
    </div>
</script>

resources/views/order/inc/_js_index.blade.php
<script id="js-validation-errors" type="text/template">
    <div class="alert alert-danger">
        <ul>
            <% _.each(items, function (error) { %>
                <li><%= error[0] %></li>
            <% }); %>
        </ul>
    </div>
</script>

resources/views/order/inc/_order_items.blade.php
@foreach($orders as $order)
    <div class="order-item" data-link="{{ ($order->status != 'new' && user_account_type('client')) ? url('order/show/' . $order->id) : url('order/edit/' . $order->id) }}">
        <div>
            <div class="order-number">
                <span class="number">№</span> {{ ($order->product_code != null) ? fix_product_code($order->product_code) : '...' }}
                @if ($order->chat_count > 0)
                    <span class="order-notification">{{ $order->chat_count }}</span>
                @endif
            </div>
            <span>{{ (!empty($order->request_number)) ? $order->request_number : '' }}</span>
        </div>
        <div class="order-date-start {{ (!$order->ready_date) ? 'fix-order-date' : '' }}">
            @if ($order->desired_date)
                {{ to_calendar_date($order->desired_date) }}
                <span>Отгрузка</span>
            @else
                &nbsp;
            @endif
        </div>
        <div>
            @if ($order->ready_date)
                {{ to_calendar_date($order->ready_date) }}
                <span>Доставка</span>
            @else
                &nbsp;
            @endif
        </div>
        <div class="{{ !user_account_type(['manager', 'admin']) ? 'fix-for-client' : '' }}">
            {{ order_delivery_name($order->delivery_type) }}
            <span>Тип поставки</span>
        </div>
        @if (user_account_type(['manager', 'admin']))
            <div>
                {{ $order->client->name }}
                <span>Клиент</span>
            </div>
        @endif
        <div class="order-positions-cell {{ !user_account_type(['manager', 'admin']) ? 'fix-for-client' : '' }}">
            <a href="#" class="order-positions u u-dotted js-show-positions">Позиции</a>
            @if (!empty($order->items))
                <div class="order-positions-popup">
                    <div class="order-positions-popup-container">
                        <table>
                            <thead>
                                <tr>
                                    <th>Код товара</th>
                                    <th>Наименование</th>
                                    <th>Итоговая площадь,&nbsp;м²</th>
                                    <th>Кол-во</th>
                                    <th>Стоимость</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $total = 0;
                                @endphp
                                @foreach ($order->items as $item)
                                    <tr>
                                        <td>{{ ($item->nomenclature->sku) ? $item->nomenclature->sku : '—' }}</td>
                                        <td>{{ $item->nomenclature->title }}</td>
                                        @php
                                            $area = ($item->cnt > 1) ? $item->cnt * $item->nomenclature->area : $item->nomenclature->area;
                                        @endphp
                                        <td>{{ snumb_format($area) }}</td>
                                        <td>
                                            {{ snumb_format($item->cnt) }}
                                            @if ($item->amount > 0)
                                                <span>x {{ snumb_format($item->amount / $item->cnt) }} руб.</span>
                                            @endif
                                        </td>
                                        <td>{{ ($item->amount > 0) ? snumb_format($item->amount) .' руб.' : '—'}}</td>
                                    </tr>
                                    @php
                                        $total += ($item->amount > 0) ? $item->amount : 0
                                    @endphp
                                @endforeach
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td>Итого</td>
                                    <td>{{ ($total > 0) ? snumb_format($total) .' руб.' : '—' }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                @if ($total > 0)
                    <span>{{ snumb_format($total) .' руб.' }}</span>
                @endif
            @endif
        </div>
        <div class="order-status-cell">
            <div class="order-status order-status-{{ $order->status }}">{{ order_status_name($order->status) }}</div>
            <div class="popup-menu-container">
                <div class="icon-more js-show-popup-menu"></div>
                <div class="popup-menu">
                    <ul>
                        <li>
                            @if ($order->status != 'new' && user_account_type('client'))
                                <a href="{{ url('order/show/' . $order->id) }}">Просмотр</a>
                            @else
                                <a href="{{ url('order/edit/' . $order->id) }}">Изменить</a>
                            @endif
                        </li>
                        @if ($order->product_code != null)
                            <li>
                                <a href="#" class="js-copy-order">Копировать</a>
                                <form action="{{ url('order/copy/' . $order->id) }}" method="POST">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        @endif
                        <li>
                            <a href="#" class="js-delete-order">Удалить</a>
                            <form action="{{ url('order/delete/' . $order->id) }}" method="POST">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
            <span>Дата создания: {{ to_calendar_date($order->date) }}</span>
        </div>
    </div>
@endforeach